[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/signup.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 